//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoesItSuck.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Review
    {
        public int Review_ID { get; set; }

        [Required()]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        [Required()]
        public string Body { get; set; }
        public string Link { get; set; }
        public string Category { get; set; }

        [Required(ErrorMessage = "Rating is required.")]
        [RegularExpression("[1-5]", ErrorMessage="Rating must be between 1 and 5.")]
        [Range(typeof(byte),"1","5", ErrorMessage="Rating must be between 1 and 5.")]
        public byte Rating { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
