//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoesItSuck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Review_ID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Link { get; set; }
        public string Category { get; set; }
        public byte Rating { get; set; }
        public System.DateTime Date_Created { get; set; }
    }
}
