//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoesItSuck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review_Tag_Rel
    {
        public int Review_Tag_Rel_ID { get; set; }
        public int Review_ID { get; set; }
        public int Tag_ID { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual Review_Tag_Rel Review_Tag_Rel1 { get; set; }
        public virtual Review_Tag_Rel Review_Tag_Rel2 { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
