//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoesItSuck.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Review_Tag_Rel = new HashSet<Review_Tag_Rel>();
        }
    
        public int Tag_ID { get; set; }
        public string Tag_Name { get; set; }
        public System.DateTime Date_Created { get; set; }
    
        public virtual ICollection<Review_Tag_Rel> Review_Tag_Rel { get; set; }
    }
}
